### ISSUE TITLE
Use solution files to find projects

### ISSUE THREAD

**Issue by luizbon** [ecoAPM/dotnet-libyear#175]
As a developer, I want to use a solution file (.sln), so that I don't need to specify each project to parse.

Acceptance Criteria:

dotnet libyear Solution.sln

It should parse the solution and evaluate all projects in it.

**Comment by SteveDesmond-ca** [comment]
Are there projects in the root directory that aren't part of the solution?

Specifying the root directory should locate all the projects within it.

**Comment by luizbon** [comment]
I tried using `dotnet libyear` and `dotnet libyear ./`, both commands returned the same output.
It picks up only one file, `Directory.Build.props`, and stops processing.

I have a solution with many projects and would like to have a similar experience as `dotnet libyear src/proj1.csproj src/proj2.csproj` and so on.

**Comment by luizbon** [comment]
Looking at the code, I can see this is where it causes that behaviour.
```
	public async Task<IReadOnlyCollection<IProjectFile>> GetProjectsInDir(string dirPath)
	{
		var dir = _fileSystem.DirectoryInfo.New(dirPath);
		var projectFiles = await FindProjectsInDir(dir, SearchOption.TopDirectoryOnly);
		return projectFiles.Any()
			? projectFiles
			: await FindProjectsInDir(dir, SearchOption.AllDirectories);
	}
```

Since it finds a `project` in the root folder, it does not try to search for sub-folders.

An option could be introducing a flag to search all sub-folders regardless.

**Comment by SteveDesmond-ca** [comment]
💯 a `-r`|`--recursive` flag should be pretty quick and easy to implement 🤞🏻

**Comment by luizbon** [comment]
Thanks @SteveDesmond-ca,
I have created a PR with that change.
Please let me know if it is good.

**Comment by SteveDesmond-ca** [comment]
Completed in #176 -- thanks again!
