### ISSUE TITLE
Wildcard on minor or patch versions of packages are not supported.

### ISSUE THREAD

**Issue by dulsi** [ecoAPM/dotnet-libyear#181]
**Steps to reproduce**
1. Create a project.
2. Add a package.
3. Modify the csproj file to specify wildcard for the minor version. For example change:
`<PackageReference Include="NuGet.Protocol" Version="6.9.1" />`
to:
`<PackageReference Include="NuGet.Protocol" Version="6.*" />`
4. Run libyear on the project.

**Expected behavior**
Should find the latest version with major version of 6 and use it as the current version for the project.

**Observed behavior**
Exception due to failure to parse the version number.

**Comment by SteveDesmond-ca** [comment]
👍🏻 at the very least it shouldn't crash 😅

**Comment by SteveDesmond-ca** [comment]
Thanks for taking the time to create this issue! The changes have been implemented and will be released shortly in v8.3.0.
